name: flutterfromzero
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get_cli: ^1.8.1
  get: 4.6.5
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter:
  assets:
    - assets/movie1.jpg
    - assets/movie2.jpg
    - assets/movie3.jpg
    - assets/movie4.jpg
    - assets/movie5.jpg
    - assets/movie6.jpg
    - assets/
  uses-material-design: true
